/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CatchCard: typeof import('./src/components/CatchCard.vue')['default']
    FishBadge: typeof import('./src/components/FishBadge.vue')['default']
    LEchart: typeof import('./src/components/LEchart.vue')['default']
    SpotCard: typeof import('./src/components/SpotCard.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    WeatherMini: typeof import('./src/components/WeatherMini.vue')['default']
  }
}

// For TSX support
declare global {
  const CatchCard: typeof import('./src/components/CatchCard.vue')['default']
  const FishBadge: typeof import('./src/components/FishBadge.vue')['default']
  const LEchart: typeof import('./src/components/LEchart.vue')['default']
  const SpotCard: typeof import('./src/components/SpotCard.vue')['default']
  const TabBar: typeof import('./src/components/TabBar.vue')['default']
  const WeatherMini: typeof import('./src/components/WeatherMini.vue')['default']
}