-- FishX 8 鱼种初始化数据
-- 导入到 fish_species 表

BEGIN TRANSACTION;

INSERT INTO fish_species (id, zh_name, emoji, common_names, scientific_name, family, difficulty, water_layer, feeding, season, weight_range, distribution, subtitle, description, one_fish_one_name, fun_facts, taste, tactics, copywriting_seeds, related_species, created_at, updated_at) VALUES ('sp-001', '鲫鱼', '🐟', '["鲫瓜子", "月鲫", "河鲫"]', 'Carassius auratus', '鲤科 Cyprinidae · 鲫属 Carassius', '易', '底层', '杂食', '["春", "夏", "秋", "冬"]', '0.2-1.0kg（常见 0.3-0.5kg）', '全国淡水水域', '为什么北方钓友管它叫"鲫瓜子"？', '我国最常见、分布最广的淡水鱼之一。适应力极强，号称"淡水小强"。群居、杂食偏植物，从南到北四季可钓。', '因体侧扁、背隆起、形似瓜子而得名"鲫瓜子"。古书写作"鲒鱼"（鳞大而少）。南方俗称"河鲫"、"月鲫"。', '耐低氧极强，新手第一条鱼多是它。冬季其他鱼不咬钩时它仍咬。"鲫鱼"是钓鱼的入门老师。', '"春吃鲫夏吃鲤"。春季最肥美，炖汤奶白鲜甜，传统食疗圣品。刺多但肉嫩。', '台钓万能组合：商品饵+蚯蚓双钩，一荤一素。夏秋早晚最佳；冬季红虫/蚯蚓深水钓底。', '{"得意": ["斤头十足！🎣 鲫鱼上岸！", "今日份加菜，鲫鱼报到🐟", "野生的，永远的神！"], "谦虚": ["给口了，谢谢鱼～", "小幸运，鲫鱼也来报到", "不空军就是胜利"], "搞笑": ["鱼：你礼貌吗？/ 我：不太礼貌", "鲫鱼：完了芭比Q了", "钓了个寂寞·不对，钓了条鲫鱼"], "专业": ["{temp}°C / {pressure}hPa / 鲫鱼活性窗口", "气压{pressure}稳定,底栖杂食活性↑", "商品饵+蚯蚓组合,鲫鱼老套路"], "极简": ["🎣 {weight} · 鲫鱼 · {spot}", "📍 {spot} · {time}", "🐟 鲫 · {weight}"]}', '["sp-002", "sp-003", "sp-008"]', '2026-06-25T00:00:00Z', '2026-06-25T00:00:00Z');
INSERT INTO fish_species (id, zh_name, emoji, common_names, scientific_name, family, difficulty, water_layer, feeding, season, weight_range, distribution, subtitle, description, one_fish_one_name, fun_facts, taste, tactics, copywriting_seeds, related_species, created_at, updated_at) VALUES ('sp-002', '鲤鱼', '🐠', '["鲤子", "黄河鲤", "红鲤"]', 'Cyprinus carpio', '鲤科 Cyprinidae · 鲤属 Cyprinus', '中', '底层', '杂食偏肉', '["春", "夏", "秋"]', '1-10kg（常见 1-3kg）', '全国，江河湖库', '鲤鱼真的能"跳龙门"吗？', '我国养殖历史最悠久的鱼，象征"吉祥有余"。底栖杂食，力气大，手感十足。警惕性极高，新手易"惊窝"。', '因鳞大而整齐排列象征"鳞甲"。"鲤"字最早见于《诗经》。"鲤鱼跳龙门"出自《埤雅·释鱼》，传说黄河鲤跳过龙门即化龙。', '警惕性高，会"涮饵"——反复试探不吞。新手常被涮到崩溃，老手用"调灵钓钝"或"搓小饵"应对。越大越聪明。', '红烧/糖醋经典。"无鲤不成席"，宴客必备。黄河鲤最出名。', '底钓为主，饵料偏甜腥（红薯/玉米/商品饵）。夏季早晚窗口，避中午。8 字遛鱼法是核心。', '{"得意": ["野鲤上岸！🎣 力气真大！", "这条够一桌了", "今日大物"], "谦虚": ["小鲤报到，请多关照", "运气来了挡不住"], "搞笑": ["鲤鱼：又来一个送饵的", "遛了10分钟,鱼没累我先累"], "专业": ["{temp}°C + 搓饵 + 底钓鲤鱼窗口", "气压{pressure}鲤鱼活性↑", "8字遛鱼法,大鲤必备"], "极简": ["🎣 {weight} · 鲤鱼 · {spot}", "📍 {spot} · 跳龙门", "🐠 鲤 · {weight}"]}', '["sp-001", "sp-003", "sp-008"]', '2026-06-25T00:00:00Z', '2026-06-25T00:00:00Z');
INSERT INTO fish_species (id, zh_name, emoji, common_names, scientific_name, family, difficulty, water_layer, feeding, season, weight_range, distribution, subtitle, description, one_fish_one_name, fun_facts, taste, tactics, copywriting_seeds, related_species, created_at, updated_at) VALUES ('sp-003', '草鱼', '🐡', '["草鲩", "混子", "鲩鱼"]', 'Ctenopharyngodon idella', '鲤科 Cyprinidae · 草鱼属', '中', '中下层', '草食', '["夏", "秋"]', '2-10kg（常见 2-4kg）', '全国，大水面为主', '草鱼真的只吃草吗？', '典型草食鱼种，因食草得名。生长快、个体大，是钓鱼人最爱的"大物"之一。警惕性极高，难钓。', '因主食水草而得名。古称"鲞"或"鳝"。有些地方叫"草鲩"、"混子"。', '草鱼不仅吃草，还吃蚯蚓、商品饵、嫩玉米。夏季涨水期最活跃。新手钓不到，老手也常空军——是"实力检验鱼"。', '个体大、肉紧实，红烧/水煮鱼/酸菜鱼/剁椒鱼头均可。', '夏秋早晚最佳。钓浮（草鱼在水面吃草）或钓底。饵料：嫩玉米/芦苇尖/商品饵。打窝用青草捆。', '{"得意": ["大物上岸！草鱼！", "这条够吃一个月", "今日份：巨物"], "谦虚": ["草鱼也能钓到，运气不错"], "搞笑": ["草鱼：你怎么知道我爱吃玉米"], "专业": ["{temp}°C + 嫩玉米 + 草鱼活性", "涨水期,草鱼靠岸"], "极简": ["🎣 {weight} · 草鱼 · {spot}", "🐡 草 · {weight}"]}', '["sp-001", "sp-002", "sp-008"]', '2026-06-25T00:00:00Z', '2026-06-25T00:00:00Z');
INSERT INTO fish_species (id, zh_name, emoji, common_names, scientific_name, family, difficulty, water_layer, feeding, season, weight_range, distribution, subtitle, description, one_fish_one_name, fun_facts, taste, tactics, copywriting_seeds, related_species, created_at, updated_at) VALUES ('sp-004', '鲈鱼', '🐟', '["加州鲈", "七星鲈", "大口黑鲈"]', 'Micropterus salmoides', '太阳鱼科 Centrarchidae · 黑鲈属', '中', '中上层', '肉食（掠食）', '["春", "夏", "秋"]', '0.5-5kg（常见 0.5-2kg）', '南方为主，路亚对象鱼', '为什么海鲈比河鲈贵 10 倍？', '路亚人的"梦中情人"，掠食凶猛，咬钩瞬间"爆炸手感"。分海鲈和淡水鲈，习性差异大。海鲈肉质更鲜。', '体侧有斑点似星而得名"七星鲈"（海鲈）。加州鲈由美国引进，又叫"大口黑鲈"。路亚人统称"鲈鱼"。', '鲈鱼有"窗口期"——清晨傍晚最活跃，中午几乎不咬。路亚新手最痛："看到鱼不咬"。', '清蒸最佳，肉质细嫩少刺。海鲈刺少肉多，比河鲈贵 5-10 倍。', '路亚为主。米诺/铅头钩/软虫。清晨傍晚窗口，浅滩结构区。操作要"抽-停-抽"。', '{"得意": ["爆扣！鲈鱼上岸！", "手感爆炸", "路亚人的高光时刻"], "谦虚": ["小鲈报到，请多指教"], "搞笑": ["鲈鱼：怎么又是这个饵", "米诺:听说你想吃我"], "专业": ["{temp}°C + 清晨窗口 + 米诺", "结构区,鲈鱼藏身处"], "极简": ["🎣 {weight} · 鲈鱼 · {spot}", "🎏 鲈 · {weight}"]}', '["sp-005"]', '2026-06-25T00:00:00Z', '2026-06-25T00:00:00Z');
INSERT INTO fish_species (id, zh_name, emoji, common_names, scientific_name, family, difficulty, water_layer, feeding, season, weight_range, distribution, subtitle, description, one_fish_one_name, fun_facts, taste, tactics, copywriting_seeds, related_species, created_at, updated_at) VALUES ('sp-005', '翘嘴', '🎏', '["翘嘴鲌", "翘嘴红鲌", "刁子鱼"]', 'Culter alburnus', '鲤科 Cyprinidae · 鲌属', '中', '中上层', '肉食', '["夏", "秋"]', '0.3-3kg（常见 0.5-1kg）', '全国，水库/江河', '为什么叫"翘嘴"？看嘴就知道', '因下颌突出向上翘而得名。路亚和台钓双料对象，攻击性强，咬钩凶猛。', '因下颌明显上翘而得名。又叫"翘嘴鲌"、"翘嘴红鲌"。南方有些地方叫"刁子鱼"。', '翘嘴是"水面杀手"，清晨傍晚在水面追小鱼，发出"啪啪"声——听到这种声音基本有戏。', '肉质细嫩，清蒸/红烧均可。鱼越大越值钱。', '路亚亮片/米诺最佳。台钓用活饵（小白条）。水面系饵（波爬）效果好。', '{"得意": ["爆扣！翘嘴！", "水面开花！", "听到水声就知道有戏"], "谦虚": ["小翘报到"], "搞笑": ["翘嘴:听说你在找我"], "专业": ["{temp}°C + 清晨窗口 + 亮片", "水面系,翘嘴专用"], "极简": ["🎣 {weight} · 翘嘴 · {spot}", "🎏 翘 · {weight}"]}', '["sp-004"]', '2026-06-25T00:00:00Z', '2026-06-25T00:00:00Z');
INSERT INTO fish_species (id, zh_name, emoji, common_names, scientific_name, family, difficulty, water_layer, feeding, season, weight_range, distribution, subtitle, description, one_fish_one_name, fun_facts, taste, tactics, copywriting_seeds, related_species, created_at, updated_at) VALUES ('sp-006', '罗非鱼', '🐠', '["非洲鲫", "福寿鱼", "尼罗罗非"]', 'Oreochromis niloticus', '丽鱼科 Cichlidae · 罗非鱼属', '中', '中下层', '杂食偏植', '["夏", "秋"]', '0.3-2kg（常见 0.5-1kg）', '南方（两广、海南、福建、云南）', '为什么南方水库罗非这么难钓？', '原产非洲，1956 年引入中国。耐热耐低氧，南方水库最常见。警惕性极高，新手爆护老手空军的典型。', '因形似"非洲鲫鱼"而得名"罗非鱼"，也叫"非洲鲫"、"福寿鱼"。两广钓友最痛——不请自来，吃饵不咬钩。', '南方钓鱼佬的"公敌"——黑坑抢食、饵料被它偷光。专钓罗非要用"冷冻饵+南极虾"，腥味要重。', '刺少肉多，清蒸/红烧/烤鱼均可。海南罗非出口为主。', '腥饵重窝。冷冻饵（秋刀鱼+南极虾）效果最好。底钓+小钩细线。罗非嘴小，线组要细。', '{"得意": ["罗非爆护！", "南方佬的胜利"], "谦虚": ["小罗报到"], "搞笑": ["罗非:南方水库我最大", "又想钓我?没门"], "专业": ["{temp}°C + 冷冻饵 + 罗非活性", "南方水库,罗非主场"], "极简": ["🎣 {weight} · 罗非 · {spot}", "🐠 罗 · {weight}"]}', '[]', '2026-06-25T00:00:00Z', '2026-06-25T00:00:00Z');
INSERT INTO fish_species (id, zh_name, emoji, common_names, scientific_name, family, difficulty, water_layer, feeding, season, weight_range, distribution, subtitle, description, one_fish_one_name, fun_facts, taste, tactics, copywriting_seeds, related_species, created_at, updated_at) VALUES ('sp-007', '鲶鱼', '🐟', '["胡子鲶", "土鲶", "南方大口鲶"]', 'Silurus asotus', '鲶科 Siluridae · 鲶属', '易', '底层', '肉食', '["春", "夏", "秋"]', '0.5-10kg（南方大口鲶更大）', '全国，江河/水库', '为什么夜钓鲶鱼最容易爆护？', '夜行性底栖肉食鱼，无鳞有须。白天藏深水洞穴，夜晚出动觅食。夜钓鲶鱼是夏季最爽的钓法。', '因体表黏液多而得名"鲶"（"黏"同音）。又叫"鲶鱼胡子"、"胡子鲶"。南方大口鲶可达数十斤。', '鲶鱼视力差，靠须和侧线感知猎物。鸡肝/鸡肠是经典饵。听到"嘎嘎"声就知道咬钩了。', '红烧/酸菜鱼/水煮鱼/鲶鱼豆腐汤。肉多刺少，老幼皆宜。', '夜钓为主（傍晚到午夜）。底钩大饵（鸡肝/青蚯蚓/活鱼）。粗线大钩，不怕切线。', '{"得意": ["夜钓爆护！鲶鱼！", "大物！胡子鲶！"], "谦虚": ["夜钓小确幸"], "搞笑": ["鲶鱼:又上夜班的来了"], "专业": ["夜钓 + 鸡肝 + 底钩", "{temp}°C + 夜行窗口"], "极简": ["🎣 {weight} · 鲶鱼 · {spot}", "🐟 鲶 · {weight}"]}', '[]', '2026-06-25T00:00:00Z', '2026-06-25T00:00:00Z');
INSERT INTO fish_species (id, zh_name, emoji, common_names, scientific_name, family, difficulty, water_layer, feeding, season, weight_range, distribution, subtitle, description, one_fish_one_name, fun_facts, taste, tactics, copywriting_seeds, related_species, created_at, updated_at) VALUES ('sp-008', '鳊鱼', '🐟', '["武昌鱼", "团头鲂", "鲂鱼"]', 'Megalobrama amblycephala', '鲤科 Cyprinidae · 鲂属', '中', '中层', '草食偏杂', '["春", "夏", "秋"]', '0.3-1.5kg（常见 0.5-1kg）', '全国，长江中下游', '鳊鱼和武昌鱼到底什么关系？', '体侧扁呈菱形，因"鳊"得名。武昌鱼是鳊鱼的一种（团头鲂），因毛泽东"才饮长沙水，又食武昌鱼"而闻名。', '"鳊"指体侧扁。武昌鱼是团头鲂的别称，因产自湖北武昌而得名。古人称"鲂"。', '"中产钓友"最爱——比鲫鱼大，比草鱼好钓。群居性强，钓到一条常常一串。', '清蒸最佳，肉质细嫩。"才饮长沙水，又食武昌鱼"让其文化附加值极高。', '台钓半水（鳊鱼在中层）。饵料偏香甜（玉米/麦麸/商品饵）。手竿要轻。', '{"得意": ["鳊鱼上岸！一串！", "武昌鱼,毛泽东认证"], "谦虚": ["小鳊报到"], "搞笑": ["鳊鱼:又来一群"], "专业": ["{temp}°C + 半水 + 鳊鱼窗口", "气压{pressure},鳊鱼活性"], "极简": ["🎣 {weight} · 鳊鱼 · {spot}", "🐟 鳊 · {weight}"]}', '["sp-001", "sp-002", "sp-003"]', '2026-06-25T00:00:00Z', '2026-06-25T00:00:00Z');

COMMIT;
